spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/logic
    username: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/logic
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  thymeleaf:
    mode: HTML
    cache: false
logging:
    level:
      root: INFO
      com.logics.logics: DEBUG
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
